curve_game_web_index:
    path:     /
    defaults: { _controller: CurveGameWebBundle:Index:index }
    methods: GET

curve_game_web_index2:
    path:     /index2
    defaults: { _controller: CurveGameWebBundle:Index2:index}
    methods: GET