curve_game_cms_index:
  path: /
  defaults:
    _controller: CurveGameCmsBundle:Player:index
  methods: GET

curve_game_cms_login:
  path: /login
  defaults:
    _controller: CurveGameCmsBundle:Security:login
  methods: [GET,POST]

curve_game_cms_logout:
  path: /logout
  defaults:
    _controller: CurveGameCmsBundle:Security:logout
  methods: [GET]

curve_game_cms_player_edit:
  path: /edit/{id}
  defaults:
    _controller: CurveGameCmsBundle:Player:edit
  methods: [GET]

curve_game_cms_player_update:
  path: /update/{id}
  defaults:
    _controller: CurveGameCmsBundle:Player:update
  method: [PUT,POST]
  requirements:
    id: \d+

curve_game_cms_player_deleteConfirm:
  path: /delete/{id}/confirm
  defaults:
    _controller: CurveGameCmsBundle:Player:deleteConfirm
  methods: [GET]

curve_game_cms_player_delete:
  path: /delete/{id}
  defaults:
    _controller: CurveGameCmsBundle:Player:delete
  methods: [DELETE,POST]