CurveGame\EntityBundle\Entity\Player:
    type: entity
    table: players
    repositoryClass: CurveGame\EntityBundle\Entity\PlayerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        username:
            type: string
            length: 64
            unique: true
        hash:
            type: string
            length: 64
            unique: true
        color:
            type: string
            length: 10
            nullable: true
        score:
            type: integer
            nullable: true
        timestamp:
            type: bigint
        joinDate:
            type: datetime

    manyToOne:
        status:
            targetEntity: CurveGame\EntityBundle\Entity\Status
            inversedBy: players
            joinColumn:
                name: status_id
                referencedColumnName: id
                nullable: false

    lifecycleCallbacks:
        prePersist: [prePersist]