CurveGame\EntityBundle\Entity\Status:
    type: entity
    table: null
    repositoryClass: CurveGame\EntityBundle\Entity\StatusRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: '64'
            unique: true

    oneToMany:
        players:
            targetEntity: CurveGame\EntityBundle\Entity\Player
            mappedBy: status
            orphanRemoval: true
            orderBy:
                timestamp: ASC
            cascade: ["persist", "remove"]

    lifecycleCallbacks: {  }