curve_game_api_user_register:
    path: /user/register
    defaults:
        _controller: CurveGameApiBundle:User:register
    methods: POST

curve_game_api_user_login:
    path: /user/login
    defaults:
        _controller: CurveGameApiBundle:User:login
    methods: POST

curve_game_api_test:
    path: /test/{value}
    defaults:
        _controller: CurveGameApiBundle:User:test
        value: demoPass
    methods: GET